### ISSUE TITLE
Cannot marshal objects which have more nesting depth than the API can return

### ISSUE THREAD

**Issue by rezonant** [contentful/contentful.rb#236] opened 2021-05-28 23:40 UTC
When the initial JSON for an Entry has too many nested references and thus is returned with Links, the marshal_dump for FieldsResource incorrectly returns a hash which has the Links still in it, even though the library has already done the additional requests to fetch the remaining resources. 

This is because on line 69 of fields_resource.rb in function `raw_with_links`, the `raw` hash is cloned, but that only clones the top level of the hash. The `fields` key ends up being shared between the `processed_raw` and the `@raw`. The `processed_raw` is returned, but the library replaces the realized objects with links again before Marshal.dump creates the final output. 

The end result is that upon Marshal.load, the object's marshal_load function receives a hash that has Links in it instead of the (submarshalled) objects. The solution is simply to clone the `fields` key of the `raw` object to ensure that the hash is not shared between the marshalling operation and the copy of the data maintained by the Entry object.

This showed up for us when trying to cache larger objects which exceed the max include depth allowed by the API (currently 10). It was about 12 hours of debugging to realize that this was one of the most easy to make mistakes in Ruby: not cloning a hash deep enough.

I would make a PR but its Friday and like I said I just spent 12 hours debugging this.

But here's the change that fixes it for us (we're just gonna monkey patch it in):

```ruby
    # @private
    def raw_with_links
      links = fields.keys.select { |property| known_link?(property) }
      processed_raw = raw.clone
      processed_raw['fields'] = processed_raw['fields'].clone      # THE FIX
      raw['fields'].each do |k, v|
        links_key = Support.snakify(k, @configuration[:use_camel_case])
        processed_raw['fields'][k] = links.include?(links_key.to_sym) ? send(links_key) : v
      end

      processed_raw
    end
```

**Comment by dustinbrownman** [comment] 2021-08-20 20:52
Just want to add a 👍🏻 for this issue. We want to cache the Contentful objects since fetching and building are affecting the performance of our pages. But trying to store the objects in the Rails cache is throwing exceptions for us (I don't have the exact exceptions handy at the moment 😬). I'm going to see if this monkey patching works for us and hopefully we'll be able to contribute to a PR or something to get this fixed in the codebase. Thank you for digging this up!

**Comment by rubydog** [comment] 2021-12-06 10:35
@rezonant @dustinbrownman

I am taking a deeper look at this issue. Do you have a sample case to reproduce this issue? Or can you add a testcase for fix?

**Comment by rezonant** [comment] 2021-12-06 13:58
Unfortunately not, the fix works perfectly for us and we're moving away from contentful. Best!

**Comment by earoberson** [comment] 2021-12-10 22:26
@rubydog also experiencing this issue.

Entries that have an issue caching for us include a reference, many field to at least two other entries with rich text fields and an embedded asset in that rich text field. 

Verified that the above monkey-patch works for us as well. Removing the embedded assets in the rich text field also seems to fix, but we'd like to be able to cache with the embedded asset.

Can DM with more info related to our space if needed.

**Closed** 2022-01-03 12:21 UTC
