### ISSUE TITLE
Calling Marshal.dump twice on an object makes the second one not working

### ISSUE THREAD

**Issue by elia** [contentful/contentful.rb#241] opened 2021-09-26 16:46 UTC
We uncovered this while writing an object on two different caches for reasons beyond the scope of this ticket. 

The issue can be reproduced by comparing two marshal-ed objects or trying to access its fields after rehydrating the second marshal:

```rb
contentful_entry = …
dump1 = Marshal.dump(contentful_entry)
dump2 = Marshal.dump(contentful_entry)
dump1 == dump2 # => false
Marshal.load(dump2).my_field # => error!
```

I'm not sure if the contentful object needs to be of a certain complexity before manifesting this behavior, but this issue broke our production and we're interested in having it fixed.

**Comment by rubydog** [comment] 2021-12-06 10:39
Hi @elia 

I could not reproduce this issue on my end. Do you have a specific example/entry where you encounter this issue?

Cheers

**Comment by elia** [comment] 2021-12-08 21:24
We didn't pin it down with certainty, but I think the problem manifested itself with attached image assets.

**Comment by elia** [comment] 2022-01-31 11:38
This might be related https://github.com/contentful/contentful.rb/pull/245
If I'm not mistaken images are also linked.

**Comment by rubydog** [comment] 2022-02-01 11:50
@elia can you please update contentful gem to the latest version and let me know if the problem persists?

Cheers

**Comment by rubydog** [comment] 2022-07-25 09:48
Closing because PR #245 should have fixed the issue.

**Closed by rubydog** 2022-07-25 09:48 UTC
